### ISSUE TITLE
Problemi di importazione

### ISSUE THREAD

**Issue by michelesr** [befair/sbcatalog#19]
Se vengono inseriti dati tramite una richiesta del tipo:

```
curl -XPOST -d @GF_fornitori_desmacerata.gdxp -H "Content-type: text/xml" http://localhost:5000/gdxp/supplier/
```

I dati non vengono inseriti ma esce il seguente traceback:

```
Traceback (most recent call last):
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michele/Projects/sbcatalog/sbcatalog/utils.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/michele/Projects/sbcatalog/sbcatalog/endpoints.py", line 45, in xml_collections_endpoint
    response = post_internal(resource, payl=xml2json(request.data), skip_validation=True)
  File "/home/michele/Projects/sbcatalog/sbcatalog/xml2json.py", line 42, in xml2json
    d = xmltodict.parse(xmlstring).values()[0]
TypeError: 'ValuesView' object does not support indexing
```

Il problema è dovuto al passaggio a python3, dove il metodo `values()` dei dizionari non ritorna una lista ma va castato a list():

```
l = list(l.values())
```

**Comment by michelesr** [comment]
Dopo aver messo i cast espliciti mi sono imbattuto in una nuova eccezione:

```
Traceback (most recent call last):
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michele/Projects/sbcatalog/sbcatalog/utils.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/michele/Projects/sbcatalog/sbcatalog/endpoints.py", line 45, in xml_collections_endpoint
    response = post_internal(resource, payl=xml2json(request.data), skip_validation=True)
  File "/home/michele/Projects/sbcatalog/sbcatalog/xml2json.py", line 58, in xml2json
    if isinstance(v, types.StringTypes):
AttributeError: 'module' object has no attribute 'StringTypes'
```

**Comment by warp10** [comment]
Fixato
