### ISSUE TITLE
Export GDXP broken

### ISSUE THREAD

**Issue by michelesr** [befair/sbcatalog#21]
Richiesta:

```
curl -XGET -H "Content-type: text/xml" http://localhost:5000/gdxp/supplier/
```

Traceback:

```
Traceback (most recent call last):
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/michele/Projects/sbcatalog/venv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/michele/Projects/sbcatalog/sbcatalog/utils.py", line 45, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/michele/Projects/sbcatalog/sbcatalog/endpoints.py", line 48, in xml_collections_endpoint
    l = json.loads(response.data)['_items']
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by warp10** [comment]
Fixato
